---
trigger:
  branches:
    include:
    # run only on main branch
      - main

variables:
  vmImage: ubuntu-latest
  azureServiceConnection: AdoServiceConnection

pool:
  vmImage: $(vmImage)

stages:
  - stage: Lint
    displayName: Lint and Test
    jobs:
      - job: Linting
        displayName: Linting
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Bash@3
            displayName: Install linting tools
            inputs:
              targetType: inline
              script: |
                pip install --upgrade pip
                pip install --upgrade wheel
                pip install --upgrade yamllint
                sudo apt install python3-demjson
          - task: Bash@3
            displayName: Run YAML lint on .yml files
            inputs:
              targetType: inline
              script: |
                yamllint .
          - task: Bash@3
            displayName: Run JSON Lint for all .json files
            inputs:
              targetType: inline
              script: |
                find -name '*.json' -exec jsonlint --nonstrict --verbose {} \;
      - job: Testing
        displayName: Testing
        pool:
          vmImage: $(vmImage)
        steps:
          - task: AzurePowerShell@5
            displayName: Run PowerShell Tests
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: inlineScript
              inline: |
                Install-Module -Name Pester -Force
                Install-Module Microsoft.Graph -Force
                Select-MgProfile -Name "beta"
                Invoke-Pester -CI
              azurePowerShellVersion: latestVersion
              pwsh: true
              workingDirectory: $(Build.SourcesDirectory)
          - task: PublishTestResults@2
            displayName: Publish Test Results
            inputs:
              testResultsFormat: NUnit
              testResultsFiles: "**/testResults.xml"
              failTaskOnFailedTests: true
